on: [push]

jobs:
    test_job:
        runs-on: ubuntu-latest
        name: my_name
        steps:
            - uses: actions/checkout@v2
            - id: my_id
              uses: owenpearson/test-action@v1
